server:
  port: 8000

spring:
  redis:
    host: 1.15.178.196
    port: 6379
    password: 888888
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 1.15.178.196:8848
        watch-delay: 1000
    # sentinel控制填
    sentinel:
      transport:
        dashboard: 1.15.178.196:8080
    gateway:
      routes:
        - id: cloud-system
          uri: lb://guns-cloud-system
          predicates:
            - Path=/guns-cloud-system/**
          filters:
            - JwtToken
            - PermissionAuth
            - RewritePath=/guns-cloud-system/(?<segment>.*), /$\{segment}

        - id: guns-cloud-auth
          uri: lb://guns-cloud-auth
          predicates:
            - Path=/guns-cloud-auth/**
          filters:
            - JwtToken
            - RewritePath=/guns-cloud-auth/(?<segment>.*), /$\{segment}

        # product商品服务
        - id: guns-cloud-product
          uri: lb://guns-cloud-product
          predicates:
            - Path=/guns-cloud-product/**
          filters:
            - RewritePath=/guns-cloud-product/(?<segment>.*), /$\{segment}

      # member会员服务
        - id: guns-cloud-member
          uri: lb://guns-cloud-member
          predicates:
            - Path=/guns-cloud-member/**
          filters:
            - RewritePath=/guns-cloud-member/(?<segment>.*), /$\{segment}

      # order 订单服务
        - id: guns-cloud-order
          uri: lb://guns-cloud-order
          predicates:
            - Path=/guns-cloud-order/**
          filters:
            - RewritePath=/guns-cloud-order/(?<segment>.*), /$\{segment}

# 请求鉴权token的密钥，默认过期时间1天，单位：秒
jwt:
  secret: HMk60Cww2Z4toC8kS2HDa9j1ObJgGV8a
  expiration: 86400

ribbon:
  eager-load:
    enabled: true
    clients: guns-cloud-system

feign:
  sentinel:
    # 为feign整合sentinel
    enabled: true
  client:
    config:
      # 全局配置
      default:
        # NONE不记录任何日志--BASIC仅请求方法URL,状态码执行时间等--HEADERS在BASIC基础上记录header等--FULL记录所有
        loggerLevel: full
  httpclient:
    # 让feign使用apache httpclient做请求；而不是默认的urlconnection
    enabled: true
    # feign的最大连接数
    max-connections: 200
    # feign单个路径的最大连接数
    max-connections-per-route: 50

management:
  endpoints:
    web:
      exposure:
        include: "*"
