server:
  port: 8008

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.15.178.196:3306/hc-cloud-payment?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=CTT
    username: hc-cloud-payment
    password: WwinysDGWfWHF6eR
  redis:
    host: 1.15.178.196
    port: 6379
    password: 888888
  cloud:
    nacos:
      discovery:
#        server-addr: 1.15.178.196:8848
        server-addr: 192.168.0.114:8848
        enabled: true
        register-enabled: true
        watch-delay: 1000
  main:
    allow-bean-definition-overriding: true