server:
  port: 8003

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.15.178.196:3306/hc_cloud_member?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=CTT
    username: hc_cloud_member
    password: tWP6bTSABk3HJhMY
  redis:
    host: 1.15.178.196
    port: 6379
    password: 888888
  cloud:
    nacos:
      discovery:
#        server-addr: 1.15.178.196:8848
        server-addr: 192.168.0.114:8848
        enabled: true
        register-enabled: true
        watch-delay: 1000

mybatis-plus:
  mapper-locations:
    - classpath*:cn/stylefeng/guns/cloud/member/mapper/mapping/*.xml

  configuration:
    map-underscore-to-camel-case: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      id-type: assign_id
      table-underline: true
  type-aliases-package:
#roses:
#  scanner:
#    app-code: guns-cloud-product
#    app-name: 商品服务
#    open: true
#  tenant:
#    open: false


management:
  endpoints:
    web:
      exposure:
        include: "*"

